config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'sessions/sessions', registrations: 'sessions/registrations'
  }

  get 'admin', to: 'admin#index', as: 'admin'

  get 'reload_posts', to: 'posts#reload_posts'

  root 'main#index'

  post 'add_user/:neighborhood_id', to: 'neighborhoods#add_user'
  post 'neighborhoods/:id/remove_user/:user_id', as: 'remove_user', to: 'neighborhoods#remove_user'

  post 'categories/:neighborhood_id/create', as: 'create_category', to: 'categories#create'

  resources :posts do
    member do
      post 'upvote'
      post 'downvote'
      post 'update_category'
    end
  end

  post 'comment/:post_id', to: 'comments#create', as: 'create_comment'

  get '/neighborhoods/visit/:id', to: 'neighborhoods#visit', as: 'visit'

  resources :requests do
    member do
      post 'approve', to: 'requests#approve'
    end
  end
  resources :neighborhoods do
    member do
      post 'set_active', to: 'neighborhoods#set_active'
      post 'request_to_join', to: 'neighborhoods#request_to_join'
      post 'leave', to: 'neighborhoods#leave'
      get 'inherit', to: 'neighborhoods#new'
    end
  end
  resources :categories, except: [:create]
  resources :comments, except: [:create, :destroy] do
    member do
      post 'upvote'
      post 'downvote'
      delete 'delete', to: 'comments#destroy'
    end
  end
  resources :events
  resources :messages
  resources :groups do
    member do
      post 'add_users', to: 'groups#add_users'
      get 'leave', to: 'groups#leave'
    end
  end
  resources :users

end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  score      :integer
#  comment    :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  post_id    :integer
#  user_id    :integer
#

class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/controllers/comments_controller.rb
# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  score      :integer
#  comment    :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
  before_action :set_post, only: [:create]
  before_action :authenticate_user!

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    @comment.user.comments << @comment
    @comment.post = @post
    @post.comments << @comment
    @comment.score = 0

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.js
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def upvote
    @comment.score = @comment.score + 1
    update_lead_status(@comment.user, @comment.post.neighborhood, 1)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to posts_url }
        format.js
      end
    end
  end

  def downvote
    @comment.score = @comment.score - 1
    update_lead_status(@comment.user, @comment.post.neighborhood, -1)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to posts_url }
        format.js
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @post = @comment.post
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.js
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    def set_post
      @post = Post.find(params[:post_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:score, :comment, :user_id, :post_id)
    end
end

app/helpers/comments_helper.rb
# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  score      :integer
#  comment    :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

module CommentsHelper
  def comments_button(post)
    if post.comments.count > 0
      post.comments.count.to_s + ' comments'
    else
      'Leave a comment'
    end
  end

  def can_delete_comment(user, comment)
    if comment.user_id == user.id
      true
    else
      unless user.current_neighborhood.nil?
        if is_lead(user, user.current_neighborhood)
          true
        else
          false
        end
      else
        false
      end
    end
  end
end

app/views/comments/_comment.html.erb
<% unless comment.nil? || comment.user.nil? %>
<div class="well comment foot-parent">
  <p>
    <%= comment.comment %>
    <% if can_delete_comment(current_user, comment) %>
      <%= link_to delete_comment_path(comment), remote: true, method: :delete, class: 'pull-right' do %>
        <span class="glyphicon glyphicon-remove"></span>
      <% end %>
    <% end %>
  </p>
  <br>
  <ul class="list-inline list-unstyled bottom-right">
    <li>
      <%= link_to upvote_comment_path(comment), remote: true, method: :post do %>
      <span class="glyphicon glyphicon-thumbs-up"></span>
      <% end %>
    </li>
    <li>
      <span id='comment-score-<%= comment.id %>'>
        <%= comment.score %>
      </span>
    </li>
    <li>
      <%= link_to downvote_comment_path(comment), remote: true, method: :post do %>
      <span class="glyphicon glyphicon-thumbs-down"></span>
      <% end %>
    </li>
    <li>|</li>
    <li>
      <%= comment.user.name %>
      <div class="buttons">
        <%= button_to comment.user, method: :get, class: "btn label " + tag_color(comment.user) do %>
          <%= comment.user.username %>
        <% end %>
      </div>
    </li>
    <li>|</li>
    <li>
      <span>
        <i class="glyphicon glyphicon-calendar"></i>
        <%= I18n.localize comment.updated_at, format: :post %>
      </span>
    </li>
  </ul>
</div>
<% end %>

app/views/comments/_form.html.erb
<div class="well comment foot-parent">
  <%= form_tag create_comment_path(post.id), method: :post, remote: true  do %>
    <div class="field comment-textarea">
      <%= text_area_tag :'comment[comment]', '', class: 'form-control', placeholder: 'How do you feel about this...',  id: "comments-form-" + post.id.to_s %>
    </div>
    <div class="actions text-right comment-submit">
      <%= submit_tag 'Comment', class: 'btn btn-md btn-primary', remote: true %>
    </div>
  <% end %>
</div>

app/views/comments/create.js.erb
$('#comments-<%=j @post.id.to_s %>').html("<% @post.comments.each do |comment| %><%=j render comment %><% end %>");

$('#comments-count-<%=j @post.id.to_s %>').html("<%=j comments_button(@post) %>");

$('#comments-form-<%=j @post.id.to_s %>').val('');

app/views/comments/destroy.js.erb
$('#comments-<%=j @post.id.to_s %>').html("<% @post.comments.each do |comment| %><%=j render comment %><% end %>");

app/views/comments/downvote.js.erb
$('<%=j "#comment-score-" + @comment.id.to_s %>').html("<%=j @comment.score.to_s %>");

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Score</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.score %></td>
        <td><%= comment.comment %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p>
  <strong>Score:</strong>
  <%= @comment.score %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @comment.comment %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/comments/upvote.js.erb
$('<%=j "#comment-score-" + @comment.id.to_s %>').html("<%=j @comment.score.to_s %>");