config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'sessions/sessions', registrations: 'sessions/registrations'
  }

  get 'admin', to: 'admin#index', as: 'admin'

  get 'reload_posts', to: 'posts#reload_posts'

  root 'main#index'

  post 'add_user/:neighborhood_id', to: 'neighborhoods#add_user'
  post 'neighborhoods/:id/remove_user/:user_id', as: 'remove_user', to: 'neighborhoods#remove_user'

  post 'categories/:neighborhood_id/create', as: 'create_category', to: 'categories#create'

  resources :posts do
    member do
      post 'upvote'
      post 'downvote'
      post 'update_category'
    end
  end

  post 'comment/:post_id', to: 'comments#create', as: 'create_comment'

  get '/neighborhoods/visit/:id', to: 'neighborhoods#visit', as: 'visit'

  resources :requests do
    member do
      post 'approve', to: 'requests#approve'
    end
  end
  resources :neighborhoods do
    member do
      post 'set_active', to: 'neighborhoods#set_active'
      post 'request_to_join', to: 'neighborhoods#request_to_join'
      post 'leave', to: 'neighborhoods#leave'
      get 'inherit', to: 'neighborhoods#new'
    end
  end
  resources :categories, except: [:create]
  resources :comments, except: [:create, :destroy] do
    member do
      post 'upvote'
      post 'downvote'
      delete 'delete', to: 'comments#destroy'
    end
  end
  resources :events
  resources :messages
  resources :groups do
    member do
      post 'add_users', to: 'groups#add_users'
      get 'leave', to: 'groups#leave'
    end
  end
  resources :users

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                      :integer          not null, primary key
#  username                :string
#  name                    :string
#  created_at              :datetime         not null
#  updated_at              :datetime         not null
#  email                   :string           default(""), not null
#  encrypted_password      :string           default(""), not null
#  reset_password_token    :string
#  reset_password_sent_at  :datetime
#  remember_created_at     :datetime
#  sign_in_count           :integer          default("0"), not null
#  current_sign_in_at      :datetime
#  last_sign_in_at         :datetime
#  current_sign_in_ip      :string
#  last_sign_in_ip         :string
#  forem_admin             :boolean          default("f")
#  forem_state             :string           default("pending_review")
#  forem_auto_subscribe    :boolean          default("f")
#  current_neighborhood_id :integer
#  score                   :integer
#  phone_number            :string
#  description             :string
#  user_type               :string
#  image_url               :string
#

#may can use has_and_belongs_to_many :groups :neighborhoods

class User < ActiveRecord::Base
  mount_uploader :image_url, ImageUploader

  validates :username,
    :presence => true,
    :uniqueness => {
      :case_sensitive => false
    }
  validates_format_of :username, with: /^[a-zA-Z0-9_\.]*$/, :multiline => true

  validates :user_type, inclusion: ['user', 'newser', 'admin']
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :user_groups
  has_many :groups, through: :user_groups
  belongs_to :current_neighborhood, class_name: 'Neighborhood', foreign_key: 'current_neighborhood_id'

  has_many :user_neighborhood_connections
  has_many :neighborhoods, class_name: 'Neighborhood', through: :user_neighborhood_connections
  has_many :neighborhood_leads
  has_many :lead_neighborhoods, class_name: 'Neighborhood', through: :neighborhood_leads

  has_many :requests, dependent: :destroy
  has_many :user_messages
  has_many :received_messages, class_name: 'Message', through: :user_messages
  has_many :sent_messages, class_name: 'Message', foreign_key: 'user_id'
  has_many :posts
  has_many :comments
  has_many :events

  attr_accessor :login

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      conditions[:email].downcase! if conditions[:email]
      if conditions[:username].nil?
        where(conditions).first
      else
        where(username: conditions[:username]).first
      end
    end
  end
end

app/controllers/users_controller.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  username               :string
#  password_digest        :string
#  name                   :string
#  isNewser               :integer
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  forem_admin            :boolean          default(FALSE)
#  forem_state            :string           default("pending_review")
#  forem_auto_subscribe   :boolean          default(FALSE)
#

class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  def forem_name
    email_address
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    @user.score = 0

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        unless @user.phone_number.nil? || @user.phone_number.match(/^[0-9]{3}[-.]?[0-9]{3}[-.]?[0-9]{4}$/)
          @user.phone_number = nil
          @user.save!
        end
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    if @user.user_type != 'admin'
      @user.destroy
    end

    respond_to do |format|
      if current_user.user_type == 'admin'
        format.html { redirect_to admin_url, notice: 'User was successfully destroyed.' }
        format.json { head :no_content }
      else
        format.html { redirect_to root_url, notice: 'User was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :password, :email, :phone_number, :description, :name, :user_type, :image_url)
    end
end

app/helpers/users_helper.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  username               :string
#  password_digest        :string
#  name                   :string
#  isNewser               :integer
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  forem_admin            :boolean          default(FALSE)
#  forem_state            :string           default("pending_review")
#  forem_auto_subscribe   :boolean          default(FALSE)
#

module UsersHelper
  def canEditPost(user, post)
    if post.neighborhood.users.include?(user)
      user.id == post.user_id || is_lead(user, post.neighborhood)
    else
      false
    end
  end

  def canDeletePost(user, post)
    if post.neighborhood.users.include?(user)
      user.id == post.user_id || is_lead(user, post.neighborhood)
    else
      false
    end
  end

  # def total_score(user)
  #   count = 0
  #   user.posts.each do |post|
  #     count += post.score
  #   end
  #   user.comments.each do |comment|
  #     count += comment.score
  #   end
  #   count
  # end
end

app/views/users/_form.html.erb
<style>
input[type=text] {
    width: 30%;
    padding: 12px 20px;
    margin: 8px 0;
    box-sizing: border-box;
    border: 3px solid #ccc;
    -webkit-transition: 0.5s;
    transition: 0.5s;
    outline: none;
}

input[type=text]:focus {
    border: 3px solid #555;
}

</style>


<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :phone_number %><br>
    <%= f.text_field :phone_number %>
  </div>
  <div class="field">
    <%= f.label :descrpition %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :isNewser %><br>

  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Password</th>
      <th>Email</th>
      <th>Name</th>
      <th>Isnewser</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.password %></td>
        <td><%= user.email %></td>
        <td><%= user.name %></td>
        <td></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<!-- Template by html.am -->

<body>

<main class="column" id="center">
  <article>

    <% if @user == current_user %>
    <h1>My Profile</h1>
  <% else %>
    <h1><%= @user.name %>'s Profile</h1>
    <% end %>

  </article>
</main>
<div id="center-contents-block">
  <div id="sidebar">
    <aside>
      <% if @user == current_user %>
      <h3>Hello
        <%= @user.name %>!!</h3>
    <% else %>
      <h3><%= @user.name %></h3>
      <p class="center">
        <span class="label <%= tag_color @user %> label-xs"><%= @user.username %></span>
      </p>
    <% end %>
    <br>

      <div class="center">
        <% if @user.image_url.present? %>
          <%= image_tag @user.image_url, width: '200', height: '200', class: 'img-circle', id: 'center', alt: 'profile' %>
        <% else %>
          <img alt="profile" class="img-circle" id="center" src="<%= asset_path("profile.png") %>">
        <% end %>
        <p></p>
        <%= link_to 'Send Message', 'javascript: send_to("' + @user.username.to_s + '")', class: 'btn btn-primary btn-xs btn-block white-text' %>
        <p></p>
        <% if @user == current_user %>
        <a class="btn btn-xs btn-primary btn-block" data-toggle="modal" href="#edit2">
          <span class="glyphicon glyphicon-pencil"></span>
          Change Password
        </a>

        <% end %>
      </div>
    </aside>

    <aside>
      <hr>

      <p></p>
      <% if @user.user_type != 'admin' %>
        <% if @user == current_user %>
          <%= button_to "Cancel account", user_path(@user), data: { confirm: "Are you sure?" }, method: :delete, class: "btn btn-danger btn-xs btn-block" %>
        <% elsif current_user.user_type == 'admin' %>
          <%= button_to "Delete user", user_path(@user), method: :delete, class: "btn btn-danger btn-xs btn-block" %>
        <% end %>
      <% end %>

    </aside>
    <aside>
      <div class="bs-example" id="center">
        <!-- Button HTML (to Trigger Modal) -->
        <div class="modal fade" id="edit0" role="dialog">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <button aria-hidden="true" class="close" data-dismiss="modal" type="button">&times;</button>
                <h4 class="modal-title">Edit Profile</h4>
              </div>
              <%= form_for @user, :html => {:multipart => true} do |f| %>
              <div class="modal-body">

                <div class="field">
                  <%= f.label :name %>
                  <%= f.text_field :name, required: true, autofocus: true, value: @user.name, class: 'form-control' %>
                </div>
                <div class="field">
                  <%= f.label :username %>
                  <%= f.text_field :username, required: true, value: @user.username, class: 'form-control' %>
                </div>
                <div class="field">
                  <%= f.label :Bio %>
                  <%= f.text_area :description, value: @user.description, class: 'form-control' %>
                </div>
                <div class="field">
                  <%= f.label :profile_picture %>
                  <%= f.file_field :image_url %>
                </div>
              </div>
              <div class="modal-footer">
                <%= f.submit "Save", class: "btn btn-primary" %>
                <button class="btn btn-default" data-dismiss="modal" type="button">Close</button>
              </div>
              <% end %>
            </div>

          </div>
        </div>

        <div class="modal fade" id="edit1" role="dialog">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <button aria-hidden="true" class="close" data-dismiss="modal" type="button">&times;</button>
                <h4 class="modal-title">Edit Profile</h4>
              </div>
              <%= form_for(@user) do |f| %>
              <div class="modal-body">
                <div class="field">
                  <%= f.label :phone_number %>
                  <%= f.text_field :phone_number, value: @user.phone_number, placeholder: 'Enter in the following format: XXX-XXX-XXXX', class: 'form-control' %>
                </div>
                <div class="field">
                  <%= f.label :email %>
                  <%= f.text_field :email, required: true, value: @user.email, class: 'form-control' %>
                </div>
              </div>
              <div class="modal-footer">
                <%= f.submit "Save", class: "btn btn-primary" %>
                <button class="btn btn-default" data-dismiss="modal" type="button">Close</button>
              </div>
              <% end %>
            </div>

          </div>
        </div>

        <div class="modal fade" id="edit2" role="dialog">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <button aria-hidden="true" class="close" data-dismiss="modal" type="button">&times;</button>
                <h4 class="modal-title">Change Password</h4>
              </div>
              <%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name), html: { method: :put }) do |f| %>
              <div class="modal-body">
                <%= f.error_notification %>
                <div class="form-inputs">

                  <%= f.input :current_password, placeholder: 'Current Password', required: true, input_html: { class: 'form-control'}  %>
                  <%= f.input :password, placeholder: 'Enter A New Password', required: true, hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length), input_html: { class: 'form-control'} %>
                  <%= f.input :password_confirmation, placeholder: 'Confirm', required: true, input_html: { class: 'form-control'} %>
                </div>
              </div>
              <div class="modal-footer">
                <%= f.submit "Save", class: "btn btn-primary" %>
                <button class="btn btn-default" data-dismiss="modal" type="button">Close</button>
              </div>
              <% end %>
            </div>

          </div>
        </div>
      </div>
    </div>
  </aside>
</div>

<div id="main-contents">
  <p></p>
  <div class="panel profile-nav-tabs panel-success">
    <div class="panel-heading">
      <ul class="nav nav-tabs">
        <li class="active">
          <a data-toggle="tab" href="#tab1">About</a>
        </li>
        <li>
          <a data-toggle="tab" href="#tab2">Contact</a>
        </li>
        <li>
          <a data-toggle="tab" href="#tab3">Neighborhoods</a>
        </li>
        <li>
          <a data-toggle="tab" href="#tab4">Posts</a>
        </li>
      </ul>
    </div>

    <div class="panel-body">
      <div class="tab-content">
        <div class="tab-pane fade in active" id="tab1">
          <% if @user == current_user %>
          <a class="btn btn-xs btn-primary pull-right" data-toggle="modal" href="#edit0">
            <span class="glyphicon glyphicon-pencil"></span>
            Edit
          </a>
          <% end %>
          <h2 class="text-left">
            <span class="glyphicon glyphicon-user"></span>
            About</h2>
          <div>Name:
            <%= @user.name %></div>
          <p></p>
          <div>Username:
            <%= @user.username %>
          </div>
          <% unless @user.description.nil? || @user.description == '' %>
            <p></p>
            <div>Bio:
              <%= @user.description %>
            </div>
          <% end %>
        </div>

        <div class="tab-pane fade post-scrollable" id="tab2">
          <% if @user == current_user %>
          <a class="btn btn-xs btn-primary pull-right" data-toggle="modal" href="#edit1">
            <span class="glyphicon glyphicon-pencil"></span>
            Edit
          </a>
          <% end %>
          <h2 class="text-left">
            <span class="glyphicon glyphicon-phone-alt"></span>
            Contact</h2>
          <div>
            <span class="glyphicon glyphicon-envelope"></span>:
            <%= @user.email %>
          </div>
          <% unless @user.phone_number.nil? || @user.phone_number == '' %>
            <p></p>
            <div>
              <span class="glyphicon glyphicon-phone"></span>:
              <%= @user.phone_number %>
            </div>
          <% end %>
        </div>

        <div class="tab-pane fade scrollable" id="tab3">
          <h2 class="text-left">
            <span class="glyphicon glyphicon-home"></span>
            <%= @user.name %>'s Neighborhoods
          </h2>
          <% @user.neighborhoods.each do |neighborhood| %>
        <li class="click-row pointer" onclick="goto('<%= neighborhood_path(neighborhood) %>');"><%= neighborhood.name %></li>
        <% end %>
      </div>

      <div class="tab-pane fade post-scrollable" id="tab4">
        <h2 class="text-left">
          <span class="glyphicon glyphicon-list-alt"></span>
          <%= @user.name %>'s Posts
        </h2>
        <% @user.posts.each do |post| %>
          <%= render post %>
        <% end %>
      </div>
    </div>
  </div>
</div>
</body>