config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'sessions/sessions', registrations: 'sessions/registrations'
  }

  get 'admin', to: 'admin#index', as: 'admin'

  get 'reload_posts', to: 'posts#reload_posts'

  root 'main#index'

  post 'add_user/:neighborhood_id', to: 'neighborhoods#add_user'
  post 'neighborhoods/:id/remove_user/:user_id', as: 'remove_user', to: 'neighborhoods#remove_user'

  post 'categories/:neighborhood_id/create', as: 'create_category', to: 'categories#create'

  resources :posts do
    member do
      post 'upvote'
      post 'downvote'
      post 'update_category'
    end
  end

  post 'comment/:post_id', to: 'comments#create', as: 'create_comment'

  get '/neighborhoods/visit/:id', to: 'neighborhoods#visit', as: 'visit'

  resources :requests do
    member do
      post 'approve', to: 'requests#approve'
    end
  end
  resources :neighborhoods do
    member do
      post 'set_active', to: 'neighborhoods#set_active'
      post 'request_to_join', to: 'neighborhoods#request_to_join'
      post 'leave', to: 'neighborhoods#leave'
      get 'inherit', to: 'neighborhoods#new'
    end
  end
  resources :categories, except: [:create]
  resources :comments, except: [:create, :destroy] do
    member do
      post 'upvote'
      post 'downvote'
      delete 'delete', to: 'comments#destroy'
    end
  end
  resources :events
  resources :messages
  resources :groups do
    member do
      post 'add_users', to: 'groups#add_users'
      get 'leave', to: 'groups#leave'
    end
  end
  resources :users

end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id              :integer          not null, primary key
#  body            :text
#  score           :integer
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  neighborhood_id :integer
#  title           :string
#  user_id         :integer
#  category_id     :integer
#

class Post < ActiveRecord::Base
  belongs_to :neighborhood
  belongs_to :user
  belongs_to :category
  has_many :comments
end

app/controllers/posts_controller.rb
# == Schema Information
#
# Table name: posts
#
#  id              :integer          not null, primary key
#  body            :text
#  score           :integer
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  neighborhood_id :integer
#  title           :string
#

class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :update_category, :destroy, :upvote, :downvote, :comment]
  before_action :authenticate_user!

  # GET /posts
  # GET /posts.json
  def index
    if current_user.current_neighborhood.nil?
      flash[:notice] = "Cannot view posts: No neighborhood is currently active"
      redirect_to neighborhoods_url
      @posts = nil
    else
      @posts = current_user.current_neighborhood.posts
      @posts = @posts.order(created_at: :desc)
      @posts = current_user.current_neighborhood.posts.to_a
      parent = current_user.current_neighborhood.parent
      until parent.nil?
        parent_posts = parent.posts.to_a
        parent_posts.each do |post|
          if isNewser(post.user)
            @posts.push(post)
          end
        end
        parent = parent.parent
      end
      admin = User.find_by(user_type: 'admin');
      admin.posts.each do |post|
        unless @posts.include?(post)
          @posts.push(post)
        end
      end
      @posts.sort! {|left, right| right.created_at <=> left.created_at}
    end
    @post = Post.new
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    @post.neighborhood = current_user.current_neighborhood
    @post.neighborhood.posts << @post
    @post.score = 0;

    respond_to do |format|
      if @post.save
        format.html { redirect_to posts_url }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { redirect_to posts_url }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def reload_posts
    if current_user.current_neighborhood.nil?
      @posts = nil
    else
      if params[:category] == '-1'
        @posts = current_user.current_neighborhood.posts
      else
        @posts = current_user.current_neighborhood.posts.where(category: params[:category])
      end
    end

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.js
    end
  end

  def update_category
    if is_lead(current_user, @post.neighborhood)
      @post.category_id = post_params[:category_id]

      respond_to do |format|
        if @post.save
          format.html { redirect_to posts_url, notice: 'Post was successfully updated.' }
          format.json { render :show, status: :ok, location: @post }
        else
          format.html { render :edit }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    else
      respond_to do |format|
        format.html { redirect_to posts_url, notice: 'Must be a lead to edit category.' }
        format.json { render :show, status: :ok, location: @post }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def upvote
    @post.score = @post.score + 1
    update_lead_status(@post.user, @post.neighborhood, 1)

    respond_to do |format|
      if @post.save
        format.html { redirect_to posts_url }
        format.js
      end
    end
  end

  def downvote
    @post.score = @post.score - 1
    update_lead_status(@post.user, @post.neighborhood, -1)

    respond_to do |format|
      if @post.save
        format.html { redirect_to posts_url }
        format.js
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :category_id, :comment)
    end
end

app/helpers/posts_helper.rb
# == Schema Information
#
# Table name: posts
#
#  id              :integer          not null, primary key
#  body            :text
#  score           :integer
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  neighborhood_id :integer
#  title           :string
#

module PostsHelper
end

app/views/posts/_form.html.erb
<div class="post">
  <%= form_for(@post) do |f| %>
    <div class="well">
      <div class="media">
        <div class="pull-left">
          <a href='<%= user_path(current_user) %>'>
            <% if current_user.image_url.present? %>
              <%= image_tag current_user.image_url, class: 'media-object post-profile-pic' %>
            <% else %>
              <img class="media-object post-profile-pic" src="<%= asset_path("profile.png") %>">
            <% end %>
          </a>
          <div class="field">
            <label for="category">
              Category
            </label>
            <select name="post[category_id]" class="form-control" id="category">
              <% current_user.current_neighborhood.categories.each do |category| %>
                <option value="<%= category.id %>"><%= category.name %></option>
              <% end %>
            </select>
          </div>
        </div>
        <div class="media-body">
          <h4 class="media-heading"><%=  %></h4>
          <p class="text-right"><%=  %></p>
          <% if @post.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

              <ul>
              <% @post.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>
          <p>
            <div class="field">
              <!-- <%= f.label :title %><br> -->
              <%= f.text_field :title, class: 'form-control', placeholder: 'Title' %>
            </div>
            <div class="field">
              <!-- <%= f.label :body %><br> -->
              <%= f.text_area :body, cols: 50, rows: 5, class: 'form-control', placeholder: 'Say something...' %>
            </div>
            <div class="actions">
              <%= f.submit class: 'btn btn-lg btn-success pull-right' %>
            </div>
          </p>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/_post.html.erb
<% unless post.nil? || post.user.nil? %>
<div class="post center">
  <div class="well">
    <div class="media foot-parent">
      <div class="pull-left">
        <a href="<%= user_path(post.user) %>">
          <% if post.user.image_url.present? %>
            <%= image_tag post.user.image_url, class: 'media-object post-profile-pic' %>
          <% else %>
            <img class="media-object post-profile-pic" src="<%= asset_path("profile.png") %>">
          <% end %>
        </a>
        <p>
          <%= post.user.name %>
          <%= button_to post.user, method: :get, class: "btn label " + tag_color(post.user) do %>
            <%= post.user.username %>
          <% end %>
         </p>
        <% if is_lead(current_user, post.neighborhood) %>
          <p><a href="#change-category-modal-<%= post.id %>" data-toggle="modal"><%= '<' + post.category.name + '>' unless post.category.nil? %></a></p>
        <% else %>
          <p><%= '<' + post.category.name + '>' unless post.category.nil? %></p>
        <% end %>
        <br>
        <br>
      </div>
      <div class="media-body">
        <h2 class="media-heading">
          <%= post.title %>
          <% if canDeletePost(current_user, post) %>
            <%= link_to post, method: :delete, class: 'pull-right' do %>
              <span class="glyphicon glyphicon-remove"></span>
            <% end %>
          <% end %>
        </h4>
        <hr>
        <p><%= post.body %></p>
      </div>
      <ul class="list-inline list-unstyled bottom-right">
        <li>
          <%= link_to upvote_post_path(post), remote: true, method: :post do %>
          <span class="glyphicon glyphicon-thumbs-up"></span>
          <% end %>
        </li>
        <li>
          <span id='score-<%= post.id %>'>
            <%= post.score %>
          </span>
        </li>
        <li>
          <%= link_to downvote_post_path(post), remote: true, method: :post do %>
          <span class="glyphicon glyphicon-thumbs-down"></span>
          <% end %>
        </li>
        <li>|</li>
        <li>
          <a onclick='toggle_comments(<%= post.id %>)' class="pointer">
          <i class="glyphicon glyphicon-comment"></i>
          <span id="comments-count-<%= post.id %>"><%= comments_button(post) %></span>
          </a>
        </li>
        <li>|</li>
        <li>
          <span>
            <i class="glyphicon glyphicon-calendar"></i>
            <%= I18n.localize post.created_at, format: :post %>
          </span>
        </li>
      </ul>
    </div>
    <div id="comments-section-<%= post.id %>" hidden="true">
      <div id="comments-<%= post.id %>">
        <% post.comments.each do |comment| %>
          <%= render comment %>
        <% end %>
      </div>
      <%= render partial: 'comments/form', :locals => { :post => post } %>
    </div>
  </div>
</div>

<div id="change-category-modal-<%= post.id %>" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Change Category</h4>
      </div>
      <%= form_tag update_category_post_path(post), method: :post do %>
        <div class="modal-body">
          <div class="field">
            <label for="category">
              Category
            </label>
            <select name="post[category_id]" class="form-control">
              <% post.neighborhood.categories.each do |category| %>
                <option value="<%= category.id %>"><%= category.name %></option>
              <% end %>
            </select>
          </div>
        </div>
        <div class="modal-footer">
          <%= submit_tag "Change Category", class: "btn btn-md btn-primary" %>
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      <% end %>
    </div>
  </div>
</div>
<% end %>

app/views/posts/downvote.js.erb
$('<%=j "#score-" + @post.id.to_s %>').html("<%=j @post.score.to_s %>");

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<!-- <h1>Here's What's New</h1> -->

<div class="center">

  <h1>
    <a href="<%= neighborhood_path(current_user.current_neighborhood) %>" class="undo-link"><%= current_user.current_neighborhood.name %></a>&nbsp;
    <div class="filter-div">
      <%= form_tag reload_posts_path, method: :get, id: 'filter-form', remote: true do %>
        <%= submit_tag 'Filter', class: 'btn btn-md btn-success pull-right' %>
        <select name="category" class="form-control narrow-drop-down pull-right" id='filter'>
          <option value="-1">Show All</option>
          <% current_user.current_neighborhood.categories.each do |category| %>
            <option value="<%= category.id %>"><%= category.name %></option>
          <% end %>
        </select>
      <% end %>
    </div>
  </h1>
  <hr>

  <%= render 'form' %>

  <hr>

  <div id="list-of-posts">
    <% @posts.each do |post| %>
      <%= render post %>
    <% end %>
  </div>

</div>

<br>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/reload_posts.js.erb
$('#list-of-posts').html("<% @posts.each do |post| %><%=j render post %><% end %>");

app/views/posts/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Post:</strong>
  <%= @post.body %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/posts/upvote.js.erb
$('<%=j "#score-" + @post.id.to_s %>').html("<%=j @post.score.to_s %>");