config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'sessions/sessions', registrations: 'sessions/registrations'
  }

  get 'admin', to: 'admin#index', as: 'admin'

  get 'reload_posts', to: 'posts#reload_posts'

  root 'main#index'

  post 'add_user/:neighborhood_id', to: 'neighborhoods#add_user'
  post 'neighborhoods/:id/remove_user/:user_id', as: 'remove_user', to: 'neighborhoods#remove_user'

  post 'categories/:neighborhood_id/create', as: 'create_category', to: 'categories#create'

  resources :posts do
    member do
      post 'upvote'
      post 'downvote'
      post 'update_category'
    end
  end

  post 'comment/:post_id', to: 'comments#create', as: 'create_comment'

  get '/neighborhoods/visit/:id', to: 'neighborhoods#visit', as: 'visit'

  resources :requests do
    member do
      post 'approve', to: 'requests#approve'
    end
  end
  resources :neighborhoods do
    member do
      post 'set_active', to: 'neighborhoods#set_active'
      post 'request_to_join', to: 'neighborhoods#request_to_join'
      post 'leave', to: 'neighborhoods#leave'
      get 'inherit', to: 'neighborhoods#new'
    end
  end
  resources :categories, except: [:create]
  resources :comments, except: [:create, :destroy] do
    member do
      post 'upvote'
      post 'downvote'
      delete 'delete', to: 'comments#destroy'
    end
  end
  resources :events
  resources :messages
  resources :groups do
    member do
      post 'add_users', to: 'groups#add_users'
      get 'leave', to: 'groups#leave'
    end
  end
  resources :users

end

app/models/neighborhood.rb
# == Schema Information
#
# Table name: neighborhoods
#
#  id          :integer          not null, primary key
#  name        :string
#  location    :string
#  description :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  threshold   :integer
#  parent_id   :integer
#

class Neighborhood < ActiveRecord::Base
  mount_uploader :image_url, NhoodUploader

  has_many :user_neighborhood_connections
  has_many :users, class_name: 'User', through: :user_neighborhood_connections
  has_many :neighborhood_leads
  has_many :leads, class_name: 'User', through: :neighborhood_leads

  has_many :active_users, class_name: 'User'
  has_many :categories, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :requests, dependent: :destroy
  has_many :events, dependent: :destroy

  belongs_to :parent, class_name: 'Neighborhood', foreign_key: :parent_id
  has_many :children, class_name: 'Neighborhood', foreign_key: :parent_id
end

app/controllers/neighborhoods_controller.rb
# == Schema Information
#
# Table name: neighborhoods
#
#  id          :integer          not null, primary key
#  name        :string
#  location    :string
#  description :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class NeighborhoodsController < ApplicationController
  before_action :set_neighborhood, only: [:show, :edit, :update, :destroy, :set_active, :request_to_join, :leave, :remove_user, :visit]
  before_action :authenticate_user!

  # GET /neighborhoods
  # GET /neighborhoods.json
  def index
    @neighborhoods = Neighborhood.all
  end

  def remove_user
    user = User.find_by(id: params[:user_id])
    @neighborhood.users.delete(user)
    if is_lead(user, @neighborhood) && current_user.user_type != 'admin'
      @neighborhood.leads.delete(user)
      if @neighborhood.leads.count < 1
        @neighborhood.destroy
      end
    end

    respond_to do |format|
      format.html { redirect_to neighborhoods_url, notice: 'User has been removed' }
      format.json { render :show, status: :created, location: @neighborhood }
    end
  end

  # GET /neighborhoods/1
  # GET /neighborhoods/1.json
  def show
    if @neighborhood.users.include?(current_user)
      current_user.current_neighborhood = @neighborhood
      current_user.save!
    end
    @category = Category.new
  end

  def visit
    if @neighborhood.users.include?(current_user)
      current_user.current_neighborhood = @neighborhood
      current_user.save!

      respond_to do |format|
        format.html { redirect_to posts_url }
      end
    else
      respond_to do |format|
        format.html { redirect_to neighborhoods_url }
      end
    end
  end

  # GET /neighborhoods/new
  def new
    @neighborhood = Neighborhood.new
    unless params[:id].nil?
      @parent = Neighborhood.find(params[:id])
    end
    if isNewser(current_user)
      respond_to do |format|
        format.html { redirect_to neighborhoods_url, notice: 'Newsers cannot create neighborhoods' }
      end
    end
  end

  # GET /neighborhoods/1/edit
  def edit
  end

  def leave
    @neighborhood.users.delete(current_user)
    if is_lead(current_user, @neighborhood) && current_user.user_type != 'admin'
      @neighborhood.leads.delete(current_user)
      if @neighborhood.leads.count == 0
        @neighborhood.destroy
      end
    elsif @neighborhood.users.count == 0
      @neighborhood.destroy
    end

    respond_to do |format|
      format.html { redirect_to neighborhoods_url, notice: 'You have left the neighborhood "' + @neighborhood.name + '".' }
      format.json { render :show, status: :created, location: @neighborhood }
    end
  end

  # POST /neighborhoods
  # POST /neighborhoods.json
  def create
    @neighborhood = Neighborhood.new(neighborhood_params)
    if @neighborhood.threshold.nil?
      @neighborhood.threshold = 100
    end
    @neighborhood.users << current_user
    @neighborhood.leads << current_user
    misc = Category.new()
    misc.name = 'Miscellaneous'
    misc.description = 'Default Category'
    @neighborhood.categories << misc
    if @neighborhood.save
      set_active
    else
      respond_to do |format|
        format.html { redirect_to neighborhoods_url }
      end
    end
    # respond_to do |format|
    #   if @neighborhood.save
    #     format.html { redirect_to @neighborhood, notice: 'Neighborhood was successfully created.' }
    #     format.json { render :show, status: :created, location: @neighborhood }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @neighborhood.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /neighborhoods/1
  # PATCH/PUT /neighborhoods/1.json

  def update
    respond_to do |format|
      if @neighborhood.update(neighborhood_params)
        format.html { redirect_to @neighborhood, notice: 'Neighborhood was successfully updated.' }
        format.json { render :show, status: :ok, location: @neighborhood }
      else
        format.html { render :edit }
        format.json { render json: @neighborhood.errors, status: :unprocessable_entity }
      end
    end
  end

  # def update
  #     @group = Group.find(params[:id])
  #     @user = User.find(params[:user_id])
  #     if !@group.users.find(@user)
  #         @group.users << @user
  #     end
  #   end
  # DELETE /neighborhoods/1
  # DELETE /neighborhoods/1.json
  def destroy
    @neighborhood.destroy
    respond_to do |format|
      format.html { redirect_to neighborhoods_url, notice: 'Neighborhood was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # def join
  #   @neighborhood.users << current_user unless @neighborhood.users.include?(current_user)
  #   set_active
  # end

  # POST /neighborhoods/1/request_to_join
  def request_to_join
    unless user_pending(current_user)
      @request = Request.new
      @request.user = current_user
      @request.neighborhood = @neighborhood
      @request.request_type = 'join'

      respond_to do |format|
        if @request.save
          format.html { redirect_to @neighborhood, notice: 'Request was successfully created.' }
          format.json { render :show, status: :created, location: @request }
        else
          format.html { render :new }
          format.json { render json: @request.errors, status: :unprocessable_entity }
        end
      end
    else
      respond_to do |format|
        format.html { redirect_to @neighborhood, notice: 'Request was successfully created.' }
        format.json { render :show, status: :created, location: @request }
      end
    end
  end

  def set_active
    if @neighborhood.users.include?(current_user)
      current_user.current_neighborhood = @neighborhood
    end

    respond_to do |format|
      if current_user.save
        format.html { redirect_to @neighborhood, notice: 'Neighborhood has been visited' }
        format.json { render :show, status: :created, location: @neighborhood }
      else
        format.html { redirect_to @neighborhood, notice: 'Neighborhood could not be visited' }
        format.json { render json: @neighborhood.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_neighborhood
      @neighborhood = Neighborhood.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def neighborhood_params
      params.require(:neighborhood).permit(:name, :location, :description, :threshold, :parent_id, :image_url)
    end

    def user_pending(user)
      if Request.find_by(user_id: user.id, request_type: 'join').nil?
        false
      else
        true
      end
    end
end

app/helpers/neighborhoods_helper.rb
# == Schema Information
#
# Table name: neighborhoods
#
#  id          :integer          not null, primary key
#  name        :string
#  location    :string
#  description :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

module NeighborhoodsHelper
  def user_in_neighborhood(user, neighborhood)
    return neighborhood.users.include?(user)
  end

  def user_pending(user)
    if Request.find_by(user_id: user.id, request_type: 'join').nil?
      false
    else
      true
    end
  end
end

app/views/neighborhoods/_categories.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>
        Name
      </th>
      <th>
        Description
      </th>
      <% if is_lead(current_user, @neighborhood) %>
      <th>

      </th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @neighborhood.categories.order(:name).each do |category| %>
      <tr>
        <td>
          <%= category.name %>
        </td>
        <td>
          <%= category.description %>
        </td>
        <% if is_lead(current_user, @neighborhood) %>
        <td>
          <%= button_to 'Delete', category, method: :delete, class: 'btn btn-xs btn-danger' %>
        </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/neighborhoods/_form.html.erb
<%= form_for(@neighborhood) do |f| %>
  <% if @neighborhood.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@neighborhood.errors.count, "error") %> prohibited this neighborhood from being saved:</h2>

      <ul>
      <% @neighborhood.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <style>
  body{
    <% if !@neighborhood.nil? && @neighborhood.image_url.present? %>
      background-image: url('<%= @neighborhood.image_url %>');
    <% else %>
      background-image: url("http://static.trulia-cdn.com/images/guide/guide/horizontal/home_equity_loans_the_types_pros_and_cons.jpg");
    <% end %>
    background-attachment: fixed;
    background-size: cover;
  }
  </style>
  <div class="data-hidden field">
    <% unless @parent.nil? %>
      <%= f.text_field :parent_id, value: @parent.id %>
    <% end %>
  </div>
  <div class="center content well">
    <div class="center">
        <p class="neighborhood-title">
          <div class="field">
            <%= f.text_field :name, placeholder: 'Name', value: @neighborhood.name, class: 'form-control n-name-form' %>
          </div>
        </p>
        <p>
          <div class="field">
            <%= f.text_field :location, placeholder: 'Location', value: @neighborhood.location, class: 'form-control n-location-form' %>
          </div>
        </p>
      </table>
    </div>
    <hr class="under-title">

    <div class="panel with-nav-tabs panel-success">
      <div class="panel-heading">
        <ul class="nav nav-tabs">
          <li class="active"><a href="#tab1" data-toggle="tab">Description</a></li>
          <li><a href="#tab2" data-toggle="tab">Stats</a></li>
          <li><a href="#tab3" data-toggle="tab">Background</a></li>
        </ul>
      </div>
      <div class="panel-body">
        <div class="tab-content">
          <div class="tab-pane fade in active" id="tab1">
            <div class="field">
              <%= f.text_area :description, placeholder: 'Description', value: @neighborhood.description, class: 'form-control', rows: 6 %>
            </div>
          </div>
          <div class="tab-pane fade scrollable" id="tab2">
            <div class="field text-left">
              <%= f.label :threshold %>
              <%= f.text_field :threshold, placeholder: 'threshold', value: @neighborhood.threshold, class: 'form-control n-threshold-form' %>
              <p class="threshold">
                *Threshold is used for the automatic promotion of users to leads of a neighborhood. When a user's score meets or exceeds this value, that user becomes a lead in this neighborhood.
              </p>
            </div>
          </div>
          <div class="tab-pane fade scrollable" id="tab3">
            <div class="field text-left">
              <%= f.label :change_background %>
              <%= f.file_field :image_url %>
            </div>
          </div>
        </div>
      </div>
    </div>

    <hr class="under-description">

    <p>
      <div class="actions buttons">
        <%= f.submit 'Submit', class: 'btn btn-lg btn-success' %>
      </div>
<% end %>
      <div class="buttons">
        <%= button_to 'Back', @neighborhood, class: 'btn btn-lg btn-default', method: :get %>
      </div>
    </p>
  </div>

app/views/neighborhoods/_neighborhood.html.erb
<div class="neighborhood center">
    <div class="well pointer" onclick="goto('<%= neighborhood_path(neighborhood) %>');">
        <div class="pointer">


        <h2 class="space"><%= neighborhood.name %></h2>
        <h4><%= neighborhood.location %><h4>
        <hr class="under-title">
        <div class="panel panel-success">
            <div class="panel-heading white-text">
                <span class="white-text bold">Description</span>
            </div>
            <div class="panel-body">
                <%= neighborhood.description %>
            </div>
        </div>


        </div>
    </div>
</div>

app/views/neighborhoods/_requests.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>
        Request Type
      </th>
      <th>
        User
      </th>
      <th>
        Date
      </th>
      <th>

      </th>
      <th>

      </th>
    </tr>
  </thead>
  <tbody>
    <% @neighborhood.requests.order(:created_at).each do |request| %>
      <tr>
        <td>
          <%= request.request_type %>
          <div class="buttons">
            <% if request.request_type == 'event' %>
              <%= button_to request.event, method: :get, class: "btn label label-primary" do %>
                view
              <% end %>
            <% else %>
              <%= button_to request.user, method: :get, class: "btn label " + tag_color(request.user) do %>
                view
              <% end %>
            <% end %>
          </div>
        </td>
        <td>
          <%= request.user.name %>
          <div class="buttons">
            <%= button_to request.user, method: :get, class: "btn label " + tag_color(request.user) do %>
              <%= request.user.username %>
            <% end %>
          </div>
        </td>
        <td>
          <%= I18n.l request.created_at, format: :short %>
        </td>
        <td>
          <%= button_to 'Approve', approve_request_path(request), class: 'btn btn-xs btn-success pull-right' %>
        </td>
        <td>
          <%= button_to 'Deny', request, method: :delete, class: 'btn btn-xs btn-danger pull-left' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/neighborhoods/_users.html.erb
<table class="table">
  <thead>
    <tr>
      <th>
        User
      </th>
      <th>
        Email
      </th>
      <% if is_lead(current_user, @neighborhood) %>
      <th>

      </th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @neighborhood.users.order(:name).each do |user| %>
      <tr class="<%= 'lead-row' if is_lead(user, @neighborhood) %>">
        <td>
          <%= user.name %>
          <div class="username-btn">
            <%= button_to user, method: :get, class: "btn label " + tag_color(user) do %>
              <%= user.username %>
            <% end %>
          </div>
        </td>
        <td>
          <%= user.email %>
        </td>
        <% if is_lead(current_user, @neighborhood) %>
        <td>
          <%= button_to 'Remove', remove_user_path(@neighborhood.id, user.id), class: 'btn btn-xs btn-danger left-button' %>
        </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<p class="explanation">
  *Leads for the neighborhood appear with <span class="lead-row">bold</span> text. Regular users have <span class="label label-success">green</span> username tags. Newsers have <span class="label label-primary">blue</span> username tags
</p>

app/views/neighborhoods/edit.html.erb
<!-- <h1>Editing Neighborhood</h1>
 -->
<%= render 'form' %>
<!--
<%= link_to 'Show', @neighborhood %> |
<%= link_to 'Back', neighborhoods_path %> -->

app/views/neighborhoods/index.html.erb
<h1>Neighborhoods</h1>



<% @neighborhoods.each do |neighborhood| %>
  <%= render neighborhood %>

<% end %>

<br>

<% unless isNewser(current_user) %>
<%= button_to new_neighborhood_path, class: 'fixed-btn btn btn-success white-text', method: :get do %>
<span class="glyphicon glyphicon-plus">
</span>
<%end%>
<%end%>

app/views/neighborhoods/new.html.erb
<h1>New Neighborhood</h1>

<%= render 'form' %>

app/views/neighborhoods/show.html.erb
<style>
body{
  <% if @neighborhood.image_url.present? %>
    background-image: url('<%= @neighborhood.image_url %>');
  <% else %>
    background-image: url("http://static.trulia-cdn.com/images/guide/guide/horizontal/home_equity_loans_the_types_pros_and_cons.jpg");
  <% end %>
  background-attachment: fixed;
  background-size: cover;
}

.footer {
  display: none;
}
</style>
<div class="center content well">
  <div class="center">
      <p class="neighborhood-title"><%= @neighborhood.name %></p>
      <p>
        <%= @neighborhood.location %>
      </p>
    </table>
  </div>
  <hr class="under-title">

  <div class="panel with-nav-tabs panel-success">
    <div class="panel-heading">
      <ul class="nav nav-tabs">
        <li class="active"><a href="#tab1" data-toggle="tab">Description</a></li>
        <li><a href="#tab2" data-toggle="tab">Users</a></li>
        <li><a href="#tab3" data-toggle="tab">Categories</a></li>
        <% if is_lead(current_user, @neighborhood) %>
          <li><a href="#tab4" data-toggle="tab">Requests</a></li>
        <% end %>
      </ul>
    </div>
    <div class="panel-body">
      <div class="tab-content">
        <div class="tab-pane fade in active" id="tab1">
          <%= @neighborhood.description %>
          <hr>
          <% unless @neighborhood.parent.nil? %>
            <p>
              <b>Parent Neighborhood:</b> <span class="click-row pointer" onclick="goto('<%= neighborhood_path(@neighborhood.parent) %>')"><%= @neighborhood.parent.name %></span>
            </p>
          <% end %>
          <% unless @neighborhood.children.count == 0 %>
            <p><b>Sub-Neighborhoods:</b></p>
            <ul>
              <% @neighborhood.children.each do |child| %>
                <li class="click-row pointer" onclick="goto('<%= neighborhood_path(child) %>');">
                  <%= child.name %>
                </li>
              <% end %>
            </ul>
          <% end %>
        </div>
        <div class="tab-pane fade scrollable" id="tab2">
          <%= render 'users' %>
        </div>
        <div class="tab-pane fade" id="tab3">
          <div class="scrollable">
            <%= render 'categories' %>
          </div>
          <% if is_lead(current_user, @neighborhood) %>
            <%= link_to 'New', '#new-category-modal', data: { toggle: 'modal' }, class: 'btn btn-success btn-lg pull-right' %>
          <% end %>
        </div>
        <% if is_lead(current_user, @neighborhood) %>
          <div class="tab-pane fade" id="tab4">
            <%= render 'requests' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <hr class="under-description">

  <p>
    <% unless user_in_neighborhood(current_user, @neighborhood) %>
      <% unless user_pending(current_user) %>
        <div class="buttons">
          <%= button_to 'Join', request_to_join_neighborhood_path(@neighborhood), class: 'btn btn-lg btn-success' %>
        </div>
      <% else %>
        <div class="buttons">
          <%= button_to 'Join Request Pending', '#', disabled: true, class: 'btn btn-lg btn-default' %>
        </div>
      <% end %>
    <% else %>
      <div class="buttons">
        <%= button_to 'Leave', leave_neighborhood_path(@neighborhood), class: 'btn btn-lg btn-danger', data: { confirm: 'are you sure you want to leave?' } %>
      </div>
      <% unless isNewser(current_user) %>
        <div class="buttons">
          <%= button_to 'New Sub-Neighborhood', inherit_neighborhood_path(@neighborhood), class: 'btn btn-lg btn-success', method: :get %>
        </div>
      <% end %>
      <% if is_lead(current_user, @neighborhood) %>
        <div class="buttons">
          <%= button_to 'Edit', edit_neighborhood_path(@neighborhood), class: 'btn btn-lg btn-default', method: :get %>
        </div>
      <% end %>
    <% end %>
    <div class="buttons">
      <%= button_to 'Back', neighborhoods_path, class: 'btn btn-lg btn-default', method: :get %>
    </div>
  </p>
</div>

<%= form_tag create_category_path(@neighborhood), method: :post do %>
  <div id="new-category-modal" class="modal fade">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">New Category</h4>
        </div>
        <div class="modal-body">
          <div class="field">
            <%= label_tag :name %>
            <br>
            <%= text_field_tag :name, '', class: 'form-control' %>
          </div>

          <div class="field">
            <%= label_tag :description %>
            <br>
            <%= text_field_tag :description, '', class: 'form-control', rows: 5  %>
          </div>
        </div>
        <div class="modal-footer">
          <%= submit_tag "Create Category", class: "btn btn-md btn-primary" %>
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
<% end %>